stages:
  - build
  - deploy

variables:
  DIST_DIR: dist/hire-assist-fe/browser
  ZIP_NAME: angular.zip

build:
  image: node:22
  stage: build
  script:
    - echo "Installing dependencies..."
    - npm ci
    - echo "Building Angular application..."
    - npx ng build --configuration production
    - echo "Build output:"
    - ls -la $DIST_DIR
    - echo "Renaming index.csr.html to index.html if it exists..."
    - if [ -f "$DIST_DIR/index.csr.html" ]; then mv "$DIST_DIR/index.csr.html" "$DIST_DIR/index.html"; else echo "index.csr.html not found."; fi
    - echo "Installing zip utility..."
    - apt-get update && apt-get install -y zip
    - echo "Zipping built files (contents only)..."
    - cd $DIST_DIR
    - zip -r $CI_PROJECT_DIR/$ZIP_NAME ./*
  artifacts:
    paths:
      - angular.zip

deploy:
  image: mcr.microsoft.com/azure-cli
  stage: deploy
  dependencies:
    - build
  script:
    - echo "Logging into Azure..."
    - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
    - az account set --subscription $AZURE_SUBSCRIPTION_ID
    - echo "Disabling automatic build on deployment..."
    - az webapp config appsettings set --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_WEBAPP_NAME --settings SCM_DO_BUILD_DURING_DEPLOYMENT=false

    - echo "Deploying zip package to Azure Web App..."
    - az webapp deployment source config-zip --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_WEBAPP_NAME --src $ZIP_NAME

    - echo "Setting startup command to serve Angular app with PM2 and SPA routing..."
    - az webapp config set --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_WEBAPP_NAME --startup-file "pm2 serve /home/site/wwwroot --no-daemon --spa"
    